// <auto-generated />
namespace BootstrapVillas.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class extraDocumentFieldsInBooking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(extraDocumentFieldsInBooking));
        
        string IMigrationMetadata.Id
        {
            get { return "201507071958022_extraDocumentFieldsInBooking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
